// Row-level filtering for the events and errors feeds: it gives every event/error a
// pair of stable hashes identifying "like" items, and a small filter model that hides
// (or shows only) the items a hash — or a whole service — refers to. Both feeds carry
// the same fields, so one set of functions serves them both.
//
// The grouping is deliberately cautious: it would rather split a group in two than merge
// two kinds of problem into one. Hiding a group the user did not mean to hide destroys
// information they never agreed to lose, so where the two errors are possible this code
// takes the under-grouping one, and the UI always shows what a group covers before the
// user hides it (see `groupSummary` and `filterCoverageText`).

// The fields of an event or error that seed its hashes and its service name. Both
// `ClusterEvent` and `ClusterError` carry them, so this is the shape the hashing and
// filtering functions work against.
export type FilterableItem = {
    reason: string;
    message: string;
    namespace: string;
    objectKind: string;
    objectName: string;
};

// Kubernetes' own name generators build the random parts of an object's name from one
// fixed alphabet: `bcdfghjklmnpqrstvwxz2456789` (`k8s.io/apimachinery/pkg/util/rand`).
// It has no vowels, no "y", and no "0", "1" or "3", which is what lets a generated
// segment be told apart from a hand-written one: an all-consonant segment like "jmnbk"
// is an ordinary random suffix (the alphabet is mostly consonants, so a suffix with no
// digit in it at all is unremarkable), while "plane" or "alpine3" cannot be generated,
// because Kubernetes never puts a vowel in one.
//
// A pod created by a replicaset gets a 5-character random suffix; the replicaset itself
// is named "<workload>-<pod-template-hash>", the hash being 5-10 characters of the same
// alphabet. A statefulset's pods get an ordinal instead ("postgres-0"), and a cronjob
// names each job it creates "<cronjob>-<unix-minute timestamp>" (8-10 digits — plain
// decimal, not the alphabet above).
const RANDOM_SUFFIX = /-[bcdfghjklmnpqrstvwxz2456789]{5}$/;
const POD_TEMPLATE_HASH_SUFFIX = /-[bcdfghjklmnpqrstvwxz2456789]{5,10}$/;
const ORDINAL_SUFFIX = /-(?:0|[1-9]\d{0,2})$/;
const CRONJOB_TIMESTAMP_SUFFIX = /-\d{8,10}$/;

// Removes a generated suffix from a name, leaving the name alone when it does not carry
// that suffix (and never stripping a name away to nothing).
function stripSuffix(name: string, suffix: RegExp): string {
    const stripped = name.replace(suffix, "");
    if (stripped === "" || stripped === name) {
        return name;
    }
    return stripped;
}

// The workload an object belongs to: its name with whatever suffixes Kubernetes' name
// generators added taken back off, so an event about a pod, about its replicaset, and
// about its deployment all name the one workload. Which suffixes an object can carry
// depends on what kind of object it is, so the kind decides what may be stripped and
// nothing else is touched:
//
//   Pod         a 5-character random suffix, and then (for a replicaset's pod) the
//               replicaset's own pod-template hash or (for a cronjob's pod) the job's
//               timestamp; or, for a statefulset's pod, an ordinal.
//   ReplicaSet  its pod-template hash.
//   Job         the timestamp a cronjob puts in the name of each job it creates.
//   anything    nothing: a deployment, statefulset, daemonset, node or service carries
//   else        the name a human gave it.
//
// Names not generated by Kubernetes are therefore left intact: "nginx-alpine3" and
// "etcd-kind-control-plane" keep their names, because "alpine3" and "plane" hold vowels
// and Kubernetes' generator never emits one.
export function workloadName(objectName: string, objectKind: string): string {
    const kind = objectKind.toLowerCase();

    if (kind === "pod") {
        const withoutRandom = stripSuffix(objectName, RANDOM_SUFFIX);
        if (withoutRandom === objectName) {
            // No random suffix, so the only generated suffix it can carry is a
            // statefulset ordinal.
            return stripSuffix(objectName, ORDINAL_SUFFIX);
        }
        // A replicaset's pod carries its replicaset's pod-template hash as well; a
        // cronjob's pod carries its job's timestamp. It cannot carry both.
        const withoutHash = stripSuffix(withoutRandom, POD_TEMPLATE_HASH_SUFFIX);
        if (withoutHash !== withoutRandom) {
            return withoutHash;
        }
        return stripSuffix(withoutRandom, CRONJOB_TIMESTAMP_SUFFIX);
    }

    if (kind === "replicaset") {
        return stripSuffix(objectName, POD_TEMPLATE_HASH_SUFFIX);
    }

    if (kind === "job") {
        return stripSuffix(objectName, CRONJOB_TIMESTAMP_SUFFIX);
    }

    return objectName;
}

// The named service an event or error belongs to: the namespace plus the name of the
// workload the involved object belongs to (see `workloadName`). Namespace-qualified, so
// two same-named services in different namespaces stay distinct.
export function serviceName(item: FilterableItem): string {
    return `${item.namespace}/${workloadName(item.objectName, item.objectKind)}`;
}

// True when a word in a message is the name of an object Kubernetes named itself — a pod,
// a replicaset, or a cronjob's job. The kind is not known for a name found in a message,
// so every generated shape is tried; a word with no generated suffix (an image name, a
// container name, an ordinary English word) is not one of these.
function isGeneratedName(word: string): boolean {
    if (!word.includes("-")) {
        return false;
    }
    return workloadName(word, "Pod") !== word
        || workloadName(word, "ReplicaSet") !== word
        || workloadName(word, "Job") !== word;
}

// A pod's UID, as kubelet appends to the pod it names in a message.
const UID = /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/g;

// An IPv4 address, with an optional port.
const ADDRESS = /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(?::\d+)?\b/g;

// A word that could be an object's name: letters, digits, dots and hyphens, starting and
// ending on a letter or digit. Anything else in the message (punctuation, slashes,
// underscores) separates one word from the next.
const WORD = /[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?/g;

// Normalises a message down to *what* went wrong, with the parts saying *where* it went
// wrong masked out. Masked (they identify a place, not a problem): the involved object's
// name, its namespace, the name of any other object Kubernetes named itself (so a
// replicaset's "Created pod: web-7d9f8b6c5-x2k9p" and its "...-q4m2t" are one group),
// pod UIDs, and IP addresses. Kept (they identify the problem, and two of them differing
// means two different problems): every other number — an exit code, an HTTP status, a
// count of nodes, an image tag. "Container exited with code 1" and "code 137" are
// therefore different groups, as are a 404 and a 500 probe failure: hiding one must never
// silently hide the other. Lower-cased and whitespace-collapsed, so trivial differences
// do not split a group.
export function normalizedMessage(item: FilterableItem): string {
    const objectName = item.objectName.toLowerCase();
    const namespace = item.namespace.toLowerCase();

    const masked = item.message
        .toLowerCase()
        .replace(UID, "<uid>")
        .replace(ADDRESS, "<address>")
        .replace(WORD, (word) => {
            if (objectName !== "" && word === objectName) {
                return "<object>";
            }
            if (namespace !== "" && word === namespace) {
                return "<namespace>";
            }
            if (isGeneratedName(word)) {
                return "<object>";
            }
            return word;
        });

    return masked.replace(/\s+/g, " ").trim();
}

// The details of an event or error: its reason plus its normalised message. Two items
// with the same details are "like" one another, whichever service reported them. This
// is the string the details hash is taken over.
export function detailsKey(item: FilterableItem): string {
    return `${item.reason}|${normalizedMessage(item)}`;
}

// The details of an item in a form fit to show a user: exactly what a details hash groups
// on, so the UI can always say what a filter covers before it is applied and after. The
// masked message is shown as it is hashed, placeholders and all, because the placeholders
// are the point: they are what the group ignores.
export function groupSummary(item: FilterableItem): string {
    const message = normalizedMessage(item);
    if (message === "") {
        return item.reason;
    }
    return `${item.reason}: ${message}`;
}

// FNV-1a: a small, deterministic 32-bit string hash rendered as 8 hex characters. It
// gives an item a short stable identity so like items can be recognised and filtered as
// a group. Nothing security-sensitive depends on it, so a non-cryptographic hash is
// enough (and keeps the frontend free of a crypto dependency).
function fnv1a(text: string): string {
    let hash = 0x811c9dc5;
    for (let i = 0; i < text.length; i++) {
        hash ^= text.charCodeAt(i);
        hash = Math.imul(hash, 0x01000193) >>> 0;
    }
    return hash.toString(16).padStart(8, "0");
}

// The details hash: identifies like items across every service. The same reason and the
// same normalised message give the same hash, whichever object or service reported it.
export function detailsHash(item: FilterableItem): string {
    return fnv1a(detailsKey(item));
}

// The extended hash: the details extended with the service name, so it identifies like
// items for one named service. The same details reported from a different service give a
// different extended hash.
export function extendedHash(item: FilterableItem): string {
    return fnv1a(`${serviceName(item)}|${detailsKey(item)}`);
}

// Which way a filter runs: "hide" removes every item it matches, "only" keeps just the
// items it matches (an allow-list). Both are offered at all three scopes.
export type FilterMode = "hide" | "only";

// What a filter matches on:
//   - "details"         : the details hash — like items across every service.
//   - "details-service" : the extended hash — like items for one named service.
//   - "service"         : the service name — everything from one named service.
export type FilterScope = "details" | "details-service" | "service";

// One active filter. `value` is the details hash, extended hash, or service name its
// scope compares against. `summary` and `service` describe the items it covers, so the
// UI can always show the user what is being hidden: `summary` is the group's details
// (reason plus normalised message; empty for a service-scope filter, which covers every
// item from the service whatever it says), and `service` is the service the filter is
// confined to (empty for a details-scope filter, which spans every service).
export type EventFilter = {
    mode: FilterMode;
    scope: FilterScope;
    value: string;
    summary: string;
    service: string;
};

// The value an item presents for a given scope: the hash or service name a filter of
// that scope compares against.
export function itemScopeValue(item: FilterableItem, scope: FilterScope): string {
    if (scope === "details") {
        return detailsHash(item);
    }
    if (scope === "details-service") {
        return extendedHash(item);
    }
    return serviceName(item);
}

// True when an item is one of the items a filter refers to, whether that filter hides
// them or shows only them.
export function filterMatchesItem(filter: EventFilter, item: FilterableItem): boolean {
    return itemScopeValue(item, filter.scope) === filter.value;
}

// How many of the items a filter covers: the size of the group, so the "..." menu can say
// how much a filter will take out before the user commits to it.
export function countMatchingItems(items: FilterableItem[], filter: EventFilter): number {
    return items.filter((item) => filterMatchesItem(filter, item)).length;
}

// Applies every active filter to a list of items. The "only" filters form an allow-list:
// while any is active an item must match at least one of them (OR) to survive. The "hide"
// filters then remove whatever they match, so a hide always beats an only. With no
// filters every item survives.
export function applyEventFilters<T extends FilterableItem>(items: T[], filters: EventFilter[]): T[] {
    const only = filters.filter((filter) => filter.mode === "only");
    const hide = filters.filter((filter) => filter.mode === "hide");
    return items.filter((item) => {
        if (only.length > 0 && !only.some((filter) => filterMatchesItem(filter, item))) {
            return false;
        }
        return !hide.some((filter) => filterMatchesItem(filter, item));
    });
}

// A filter's identity: its mode, scope and value. Two filters with the same key select
// the same items in the same way, so adding one twice is a no-op and removing by key is
// unambiguous.
export function filterKey(filter: EventFilter): string {
    return `${filter.mode}:${filter.scope}:${filter.value}`;
}

// Adds a filter to the active list, ignoring it when an identical one is already active.
export function addEventFilter(filters: EventFilter[], filter: EventFilter): EventFilter[] {
    if (filters.some((active) => filterKey(active) === filterKey(filter))) {
        return filters;
    }
    return [...filters, filter];
}

// Removes the filter with the given key from the active list.
export function removeEventFilter(filters: EventFilter[], key: string): EventFilter[] {
    return filters.filter((active) => filterKey(active) !== key);
}

// The six filters a row's "..." menu offers for one item: hide and show-only, each at the
// three scopes (like this / like this for this service / this whole service), in menu
// order (the three hides, then the three show-onlys).
export function rowFilterActions(item: FilterableItem): EventFilter[] {
    const service = serviceName(item);
    const summary = groupSummary(item);
    const modes: FilterMode[] = ["hide", "only"];
    return modes.flatMap((mode) => [
        {
            mode,
            scope: "details" as FilterScope,
            value: detailsHash(item),
            summary,
            service: "",
        },
        {
            mode,
            scope: "details-service" as FilterScope,
            value: extendedHash(item),
            summary,
            service,
        },
        {
            mode,
            scope: "service" as FilterScope,
            value: service,
            summary: "",
            service,
        },
    ]);
}

// The wording of a "..." menu action: what clicking it will do.
export function filterActionText(filter: EventFilter): string {
    if (filter.mode === "hide") {
        if (filter.scope === "details") {
            return "Hide all like this";
        }
        if (filter.scope === "details-service") {
            return "Hide all like this, for this service";
        }
        return "Hide all from this service";
    }
    if (filter.scope === "details") {
        return "Show only ones like this";
    }
    if (filter.scope === "details-service") {
        return "Show only ones like this, for this service";
    }
    return "Show only this service";
}

// Exactly which items a filter covers, spelled out in full: the details it groups on and
// the service it is confined to. This is what the "..." menu shows under each action, and
// what an active filter's chip carries as its tooltip, so a user can see what a filter
// takes out before they apply it and afterwards.
export function filterCoverageText(filter: EventFilter): string {
    if (filter.scope === "service") {
        return `everything from ${filter.service}`;
    }
    const where = filter.scope === "details" ? "any service" : filter.service;
    return `"${filter.summary}" from ${where}`;
}

// How long a group's details may run on a filter's chip before it is cut short. The chip
// has to stay one readable line; the full text is on its tooltip and in the "..." menu.
const CHIP_SUMMARY_LIMIT = 48;

// Shortens a group's details to fit a chip, cutting at a word so the chip does not end
// mid-word, and marking that it was cut.
function shorten(summary: string): string {
    if (summary.length <= CHIP_SUMMARY_LIMIT) {
        return summary;
    }
    const cut = summary.slice(0, CHIP_SUMMARY_LIMIT);
    const lastSpace = cut.lastIndexOf(" ");
    const kept = lastSpace > CHIP_SUMMARY_LIMIT / 2 ? cut.slice(0, lastSpace) : cut.trimEnd();
    return `${kept}…`;
}

// The wording on an active filter's chip: what it does, which service it is confined to,
// and the details of the group it covers (cut short to fit — the whole of it is on the
// chip's tooltip). The service comes before the details so that it is never the part cut
// off: a user has to be able to see the reach of every filter they have on.
export function filterChipText(filter: EventFilter): string {
    const verb = filter.mode === "hide" ? "Hide" : "Only";
    if (filter.scope === "service") {
        return `${verb}: everything from ${filter.service}`;
    }
    const where = filter.scope === "details" ? "any service" : filter.service;
    return `${verb} (${where}): ${shorten(filter.summary)}`;
}
