import { config, library } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import {
    faCircleCheck,
    faCircleXmark,
    faCircleQuestion,
    faCirclePause,
    faServer,
    faLayerGroup,
    faCube,
    faCubes,
    faDatabase,
    faSitemap,
    faDharmachakra,
    faRotate,
    faSort,
    faSortUp,
    faSortDown,
    faMagnifyingGlass,
    faSun,
    faMoon,
    faCircleHalfStroke,
    faChevronLeft,
    faChevronRight,
    faLink,
    faArrowLeft,
    faTerminal,
    faTag,
    faTriangleExclamation,
    faCopy,
    faCheck,
} from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;

library.add(
    faCircleCheck,
    faCircleXmark,
    faCircleQuestion,
    faCirclePause,
    faServer,
    faLayerGroup,
    faCube,
    faCubes,
    faDatabase,
    faSitemap,
    faDharmachakra,
    faRotate,
    faSort,
    faSortUp,
    faSortDown,
    faMagnifyingGlass,
    faSun,
    faMoon,
    faCircleHalfStroke,
    faChevronLeft,
    faChevronRight,
    faLink,
    faArrowLeft,
    faTerminal,
    faTag,
    faTriangleExclamation,
    faCopy,
    faCheck,
);
